name: distribute
on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - pyproject.toml
    - .github/workflows/build.yml
    - mkdocs.yaml
jobs:
  distribute:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: apt-get install wkhtmltopdf
    - name: Install Hatch
      uses: pypa/hatch@install
    - name: Build and deploy documentation
      run: hatch run mkdocs gh-deploy --force

