name: build
on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Hatch
      uses: pypa/hatch@install
    - uses: browser-actions/setup-chrome@v1
    - run: make build
    - name: Build and deploy documentation
      run: hatch run mkdocs gh-deploy --force

